### ISSUE TITLE
老伙计我来了，先点个STAR

### ISSUE THREAD

**Issue by oncebeloved** [jrsen/Xposed-GodMode#16]
过程太复杂了，我都看不懂，先点的STAR，希望越来越好，有个小建议，就是增加一个悬浮控件，记录的数据保存到数据库，方便增删查改，应该可以提高效率！

**Comment by kaisar945** [comment]
朕已阅
屏蔽悬浮控件已在开发计划中
添加一个悬浮控件用来选择需要屏蔽的控件也已经在开发计划中
