### ISSUE TITLE
上帝模式可能在处理recycleview或自定义adapter时存在问题

### ISSUE THREAD

**Issue by Moderpach** [jrsen/Xposed-GodMode#19]
![IMG_20200922_234323](https://user-images.githubusercontent.com/34941512/93905648-c6452f80-fd2d-11ea-9b56-196d4eab9d2b.jpg)
红框处的项删除一个或多个，重启b站后会导致没有选中的项也被删除。
eg.删除推荐服务后，重启，整页都被删除。
删除推荐服务的第一项后，重启，创作中心的第一项也被删除。

**Comment by kaisar945** [comment]
Duplicate of #22 
之前没有ListView或RecycleView之类的控件复用机制做单独处理所以会导致屏蔽失效或者混乱 目前没有想到太好的办法先放一放
