### ISSUE TITLE
无法将上帝模式应用至酷安

### ISSUE THREAD

**Issue by caiweihan** [jrsen/Xposed-GodMode#25]
我使用的是 EMUI 10.1 + 太极，上帝模式在别的软件使用正常，在试图删除酷安的控件的时候出现了问题：在应用界面打开上帝模式界面无变化，退出重进后出现每个控件的红色边框，并可以删除控件，但再次退出重进后又会复原。我本以为这是酷安对于这类软件的防御机制，但下载了一个远古版本的酷安（7.9.7）后发现问题仍然存在。这是什么原因？

**Comment by caiweihan** [comment]
[SVID_20201227_204455_1.zip](https://github.com/kaisar945/Xposed-GodMode/files/5744570/SVID_20201227_204455_1.zip)
不知道为什么上传不了视频...

**Comment by kaisar945** [comment]
看起来的确有点问题 你到酷安上帝模式评论区找一下3.0beta1版本试一下还有没有这些问题

**Comment by GuhDoy** [comment]
酷安屏蔽了xposed，在设置-关于-右上角三点-检测日志-Debug测试里取消禁用

**Comment by caiweihan** [comment]
刚刚试了试，3.0beta1版本无法使用，退回到正式版后版本后正常
