### ISSUE TITLE
安卓14+lsposed勾选系统框架重启，zygisk next失效

### ISSUE THREAD

**Issue by qianqianNotqianqian** [jrsen/Xposed-GodMode#54]
我只勾选了系统框架，重启之后zygisk next崩溃，用的kernelsu k60 HyperOS 请问是系统问题还是kernelsu的问题呢？

**Comment by c200154** [comment]
大概率就是os系统

**Comment by qianqianNotqianqian** [comment]
OK

2220401791qq.com
***@***.***








---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kaisar945/Xposed-GodMode] 安卓14+lsposed勾选系统框架重启，zygisk next失效 (Issue #54)




 
大概率就是os系统
 
&mdash;

**Comment by yyzxq1** [comment]
我的也是，升级安卓14hyperos，magisk卡开机，禁用lsp后开机。
换kernelsu安装lsp，发现开启上帝模式后就会zygisk next无法启用；关闭上帝模式正常。

**Comment by hei888** [comment]
> 我只勾选了系统框架，重启之后zygisk next崩溃，用的kernelsu k60 HyperOS 请问是系统问题还是kernelsu的问题呢？

安卓14的锅，上帝模式不支持A14，作者也不更新适配了

**Comment by qianqianNotqianqian** [comment]
OK
