### ISSUE TITLE
无法退出编辑模式

### ISSUE THREAD

**Issue by lon91ong** [jrsen/Xposed-GodMode#8]
如题, MIUI9 Mi5手机, 关机键无效, 重启手机无效
现在想要通过shell命令的kill命令结束进程,但是不知道pid
请教大侠

**Comment by lon91ong** [comment]
自己解决了
1. 提升权限,su
2. 获取pid, pidof com.viewblocker.jrsen
例如,回显得结果,1234
3. 杀进程, kill -9 1234

**Comment by jrsen** [comment]
这么杀进程真的有用么

**Comment by lon91ong** [comment]
> 这么杀进程真的有用么

没用!
后来发现从通知栏调出的酷安可以正常用, 用酷安卸载重装后正常了

**Comment by ASC8384** [comment]
我进入REC，把上帝模式删除后解决

**Comment by alexhigger** [comment]
> 我进入REC，把上帝模式删除后解决

进去REC后是在哪个文件夹下删

**Comment by ASC8384** [comment]
> 
> 
> > 我进入REC，把上帝模式删除后解决
> 
> 进去REC后是在哪个文件夹下删

上帝模式是一个APP，在REC的删除应用里可以看见

**Comment by jrsen** [comment]
执行命令monkey -p com.viewblocker.jrsen 1再按一下锁屏键就好了
